# SPDX-FileCopyrightText: 2025 Prayag Jain <prayagjain2@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

id: org.kde.Drawy
runtime: org.kde.Platform
runtime-version: '6.10'
sdk: org.kde.Sdk
command: drawy
finish-args:
    # 3D acceleration
  - --device=dri
    # X11
  - --share=ipc
    # show a window
  - --socket=fallback-x11
  - --socket=wayland

cleanup:
  - /include
  - /lib/pkgconfig
  - /share/man
  - '*.pc'
  - '*.a'
  - '*.la'

modules:
  - name: drawy
    config-opts:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
    buildsystem: cmake-ninja
    sources:
      - type: dir
        path: '.'
